name: CI Pipeline
 
on:
  push:
    branches: [main]  # Запускать только при пуше в ветку main
 
jobs:
  build:
    runs-on: ubuntu-latest  # Используем GitHub-hosted runner с Ubuntu
 
    steps:
      - uses: actions/checkout@v3  # Клонирует код из репозитория